CREATE DATABASE IF NOT EXISTS RAD_DB;
CREATE SCHEMA IF NOT EXISTS RAD_DB.PUBLIC;

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.POSITIONS (
  ACCOUNT      STRING,
  SYMBOL       STRING,
  QTY          FLOAT,
  CURRENCY     STRING,
  COST_BASIS   FLOAT,
  SOD_PRICE    FLOAT,
  LAST_PRICE   FLOAT,
  LAST_TS      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.PRICES (
  SYMBOL   STRING PRIMARY KEY,
  BID      FLOAT,
  ASK      FLOAT,
  P        FLOAT,
  TS       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.FLAGS (
  SYMBOL        STRING,
  PCT_CHANGE    FLOAT,
  SOD_PRICE     FLOAT,
  LAST_PRICE    FLOAT,
  THRESHOLD_PCT FLOAT,
  TS            TIMESTAMP_NTZ
);

CREATE OR REPLACE VIEW RAD_DB.PUBLIC.SNAPSHOT AS
SELECT
  p.ACCOUNT, p.SYMBOL, p.QTY, p.CURRENCY, p.COST_BASIS, p.SOD_PRICE,
  p.LAST_PRICE, p.LAST_TS,
  CASE WHEN p.SOD_PRICE IS NOT NULL AND p.LAST_PRICE IS NOT NULL AND p.SOD_PRICE<>0
       THEN (p.LAST_PRICE - p.SOD_PRICE)/p.SOD_PRICE END AS PCT_CHANGE_VS_SOD
FROM RAD_DB.PUBLIC.POSITIONS p;
