CREATE DATABASE IF NOT EXISTS RAD_DB;
CREATE SCHEMA IF NOT EXISTS RAD_DB.PUBLIC;

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.POSITIONS (
  ACCOUNT      STRING,
  SYMBOL       STRING,
  QTY          FLOAT,
  CURRENCY     STRING,
  COST_BASIS   FLOAT,
  SOD_PRICE    FLOAT,
  LAST_PRICE   FLOAT,
  LAST_TS      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.PRICES (
  SYMBOL   STRING PRIMARY KEY,
  BID      FLOAT,
  ASK      FLOAT,
  P        FLOAT,
  TS       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.FLAGS (
  SYMBOL        STRING,
  PCT_CHANGE    FLOAT,
  SOD_PRICE     FLOAT,
  LAST_PRICE    FLOAT,
  THRESHOLD_PCT FLOAT,
  TS            TIMESTAMP_NTZ
);
-- Canonical snapshot view (only RAD_DB.PUBLIC.POSITIONS is used)
CREATE OR REPLACE VIEW RAD_DB.PUBLIC.SNAPSHOT AS
SELECT
  p.ACCOUNT, p.SYMBOL, p.QTY, p.CURRENCY, p.COST_BASIS, p.SOD_PRICE,
  p.LAST_PRICE, p.LAST_TS,
  CASE WHEN p.SOD_PRICE IS NOT NULL AND p.LAST_PRICE IS NOT NULL AND p.SOD_PRICE<>0
       THEN (p.LAST_PRICE - p.SOD_PRICE)/p.SOD_PRICE END AS PCT_CHANGE_VS_SOD
FROM RAD_DB.PUBLIC.POSITIONS p;

-- Clients table: store demo custodians and actual custodians (accounts that upload files)
CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.CLIENTS (
  ID STRING PRIMARY KEY,
  NAME STRING,
  EMAIL STRING,
  TYPE STRING, -- 'demo' or 'custodian'
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed demo clients (3) and two actual custodians. IDs are set to human-friendly names
-- ASSUMPTION: actual custodians are named 'Custodian One' and 'Custodian Two' for now.
-- Change these names as needed to match your ingest ACCOUNT values.
INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Quantum Capital Fund','Quantum Capital Fund','contact@quantum.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Quantum Capital Fund');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Apex Growth Partners','Apex Growth Partners','info@apex.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Apex Growth Partners');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Horizon Ventures','Horizon Ventures','hello@horizon.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Horizon Ventures');

-- Two actual custodians (these represent accounts that will be created via Excel ingest)
INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Custodian One','Custodian One','custodian1@example.com','custodian'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Custodian One');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Custodian Two','Custodian Two','custodian2@example.com','custodian'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Custodian Two');

-- Seed sample positions for demo clients (these will appear in SNAPSHOT)
-- Quantum Capital Fund positions
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'AAPL', 500, 'USD', 150.0, 150.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='AAPL');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'MSFT', 300, 'USD', 280.0, 280.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='MSFT');

-- Apex Growth Partners positions
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'NVDA', 400, 'USD', 220.0, 220.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='NVDA');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'META', 350, 'USD', 180.0, 180.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='META');

-- Horizon Ventures positions
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'JPM', 450, 'USD', 135.0, 135.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='JPM');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'BAC', 700, 'USD', 28.0, 28.0
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='BAC');

-- Seed sample PRICES for the symbols above
INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'AAPL', 175.0, 175.5, 175.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='AAPL');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'MSFT', 305.0, 305.5, 305.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='MSFT');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'NVDA', 230.0, 230.5, 230.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='NVDA');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'META', 190.0, 190.5, 190.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='META');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'JPM', 140.0, 140.5, 140.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='JPM');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'BAC', 30.0, 30.5, 30.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='BAC');
