CREATE DATABASE IF NOT EXISTS RAD_DB;
CREATE SCHEMA IF NOT EXISTS RAD_DB.PUBLIC;

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.POSITIONS (
  ACCOUNT      STRING,
  SYMBOL       STRING,
  QTY          FLOAT,
  CURRENCY     STRING,
  COST_BASIS   FLOAT,
  SOD_PRICE    FLOAT,
  LAST_PRICE   FLOAT,
  LAST_TS      TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.PRICES (
  SYMBOL   STRING PRIMARY KEY,
  BID      FLOAT,
  ASK      FLOAT,
  P        FLOAT,
  TS       TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.FLAGS (
  SYMBOL        STRING,
  PCT_CHANGE    FLOAT,
  SOD_PRICE     FLOAT,
  LAST_PRICE    FLOAT,
  THRESHOLD_PCT FLOAT,
  TS            TIMESTAMP_NTZ
);
-- Canonical snapshot view (only RAD_DB.PUBLIC.POSITIONS is used)
CREATE OR REPLACE VIEW RAD_DB.PUBLIC.SNAPSHOT AS
SELECT
  p.ACCOUNT, p.SYMBOL, p.QTY, p.CURRENCY, p.COST_BASIS, p.SOD_PRICE,
  p.LAST_PRICE, p.LAST_TS,
  CASE WHEN p.SOD_PRICE IS NOT NULL AND p.LAST_PRICE IS NOT NULL AND p.SOD_PRICE<>0
       THEN (p.LAST_PRICE - p.SOD_PRICE)/p.SOD_PRICE END AS PCT_CHANGE_VS_SOD
FROM RAD_DB.PUBLIC.POSITIONS p;

-- Clients table: store demo custodians and actual custodians (accounts that upload files)
CREATE TABLE IF NOT EXISTS RAD_DB.PUBLIC.CLIENTS (
  ID STRING PRIMARY KEY,
  NAME STRING,
  EMAIL STRING,
  TYPE STRING, -- 'demo' or 'custodian'
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed demo clients (3) and two actual custodians. IDs are set to human-friendly names
-- ASSUMPTION: actual custodians are named 'Custodian One' and 'Custodian Two' for now.
-- Change these names as needed to match your ingest ACCOUNT values.
INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Quantum Capital Fund','Quantum Capital Fund','contact@quantum.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Quantum Capital Fund');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Apex Growth Partners','Apex Growth Partners','info@apex.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Apex Growth Partners');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Horizon Ventures','Horizon Ventures','hello@horizon.com','demo'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Horizon Ventures');

-- Two actual custodians (these represent accounts that will be created via Excel ingest)
INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Custodian One','Custodian One','custodian1@example.com','custodian'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Custodian One');

INSERT INTO RAD_DB.PUBLIC.CLIENTS (ID, NAME, EMAIL, TYPE)
SELECT 'Custodian Two','Custodian Two','custodian2@example.com','custodian'
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.CLIENTS WHERE ID='Custodian Two');

-- Seed sample positions for demo clients (these will appear in SNAPSHOT)
-- Quantum Capital Fund - Tech-focused growth fund
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'AAPL', 2500, 'USD', 175.25, 168.50
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='AAPL');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'MSFT', 1800, 'USD', 332.15, 328.70
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='MSFT');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'NVDA', 1200, 'USD', 445.80, 440.25
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='NVDA');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'GOOGL', 1500, 'USD', 138.50, 135.90
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='GOOGL');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'TSM', 3000, 'USD', 89.75, 87.20
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='TSM');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'AVGO', 500, 'USD', 857.30, 850.40
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='AVGO');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'AMD', 2200, 'USD', 108.45, 105.80
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='AMD');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Quantum Capital Fund', 'CRM', 1000, 'USD', 207.25, 205.40
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Quantum Capital Fund' AND SYMBOL='CRM');

-- Apex Growth Partners - Balanced growth portfolio
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'AMZN', 1200, 'USD', 131.75, 129.90
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='AMZN');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'V', 2200, 'USD', 242.30, 240.15
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='V');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'JPM', 1800, 'USD', 148.50, 146.80
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='JPM');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'HD', 900, 'USD', 298.45, 295.70
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='HD');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'PG', 1500, 'USD', 150.25, 149.30
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='PG');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'UNH', 400, 'USD', 525.80, 522.40
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='UNH');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'MA', 800, 'USD', 401.25, 398.60
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='MA');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Apex Growth Partners', 'COST', 600, 'USD', 558.90, 555.30
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Apex Growth Partners' AND SYMBOL='COST');

-- Horizon Ventures - Value and dividend focus
INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'JNJ', 2000, 'USD', 156.75, 155.40
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='JNJ');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'PFE', 4500, 'USD', 33.45, 32.90
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='PFE');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'KO', 5000, 'USD', 58.90, 58.20
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='KO');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'VZ', 4800, 'USD', 31.25, 30.80
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='VZ');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'CVX', 1800, 'USD', 166.40, 164.90
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='CVX');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'MRK', 2200, 'USD', 103.80, 102.90
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='MRK');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'PEP', 1600, 'USD', 168.25, 167.30
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='BMY');

INSERT INTO RAD_DB.PUBLIC.POSITIONS (ACCOUNT, SYMBOL, QTY, CURRENCY, COST_BASIS, SOD_PRICE)
SELECT 'Horizon Ventures', 'BMY', 3000, 'USD', 57.90, 57.20
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.POSITIONS WHERE ACCOUNT='Horizon Ventures' AND SYMBOL='BMY');

-- Seed sample PRICES for all symbols
INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'AAPL', 168.45, 168.55, 168.50, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='AAPL');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'MSFT', 328.65, 328.75, 328.70, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='MSFT');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'NVDA', 440.20, 440.30, 440.25, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='NVDA');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'GOOGL', 135.85, 135.95, 135.90, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='GOOGL');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'TSM', 87.15, 87.25, 87.20, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='TSM');

-- Insert remaining market prices
INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'AVGO', 850.35, 850.45, 850.40, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='AVGO');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'AMD', 105.75, 105.85, 105.80, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='AMD');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'CRM', 205.35, 205.45, 205.40, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='CRM');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'AMZN', 129.85, 129.95, 129.90, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='AMZN');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'V', 240.10, 240.20, 240.15, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='V');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'JPM', 146.75, 146.85, 146.80, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='JPM');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'HD', 295.65, 295.75, 295.70, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='HD');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'PG', 149.25, 149.35, 149.30, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='PG');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'UNH', 522.35, 522.45, 522.40, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='UNH');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'MA', 398.55, 398.65, 398.60, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='MA');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'COST', 555.25, 555.35, 555.30, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='COST');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'JNJ', 155.35, 155.45, 155.40, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='JNJ');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'PFE', 32.85, 32.95, 32.90, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='PFE');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'KO', 58.15, 58.25, 58.20, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='KO');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'VZ', 30.75, 30.85, 30.80, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='VZ');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'CVX', 164.85, 164.95, 164.90, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='CVX');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'MRK', 102.85, 102.95, 102.90, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='MRK');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'PEP', 167.25, 167.35, 167.30, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='PEP');

INSERT INTO RAD_DB.PUBLIC.PRICES (SYMBOL, BID, ASK, P, TS)
SELECT 'BMY', 57.15, 57.25, 57.20, CURRENT_TIMESTAMP()
WHERE NOT EXISTS (SELECT 1 FROM RAD_DB.PUBLIC.PRICES WHERE SYMBOL='BMY');
